[package]
name = "unpak"
authors = ["spuds"]
repository = "https://github.com/bananaturtlesandwich/unpak"
description = "a no-nonsense unreal pak parsing crate"
license = "MIT OR Apache-2.0"
keywords = ["modding", "parsing", "compression"]
categories = ["filesystem", "parser-implementations"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "*"
strum = { version = "*", features = ["derive"] }
aes = "*"
flate2 = "*"
hashbrown = "*"
thiserror = "*"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
