[package]
name = "unpak_cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "unpak"
path = "src/main.rs"

[dependencies]
aes = "0.8"
base64 = "0.21.0"
clap = { version = "4.1.4", features = ["derive"] }
path-clean = "0.1.0"
unpak = { version = "0.2.0", path = ".." }
