[package]
name = "repak"
repository.workspace = true
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
byteorder = "1.4"
strum = { version = "0.24", features = ["derive"] }
aes = "0.8"
flate2 = "1.0"
thiserror = "1.0"
sha1 = "0.10.5"

[dev-dependencies]
base64 = { workspace = true }
paste = "1.0.11"
